# This workflow opens and updates a pull request with a new package version
# based on code changes.

# The pull request updates the version in version.py, updates the changelog
# and creates release tags.

# For more information, see https://github.com/marketplace/actions/release-please-action
on:
  push:
    branches:
      - master

permissions:
  contents: write
  pull-requests: write
  packages: write
  deployments: read

name: release-please

jobs:
  test:
    uses: ./.github/workflows/test.yml

  release-please:
    runs-on: ubuntu-22.04
    needs: test
    steps:
      - uses: google-github-actions/release-please-action@v4.1.0
